global:

templates:
- '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 4h
  receiver: 'voximplant'


receivers:
    - name: 'voximplant'
      webhook_configs:
      - send_resolved: False
        url: http://voximplant_bot:8000/alert/2745089
